.PHONY: clean All

All:
	@echo "----------Building project:[ Split_Houses - Debug ]----------"
	@cd "Split_Houses" && "$(MAKE)" -f  "Split_Houses.mk"
clean:
	@echo "----------Cleaning project:[ Split_Houses - Debug ]----------"
	@cd "Split_Houses" && "$(MAKE)" -f  "Split_Houses.mk" clean
