.PHONY: clean All

All:
	@echo "----------Building project:[ 02_Find_Numbers_with_Even_Number_of_Digits - Debug ]----------"
	@cd "02_Find_Numbers_with_Even_Number_of_Digits" && "$(MAKE)" -f  "02_Find_Numbers_with_Even_Number_of_Digits.mk"
clean:
	@echo "----------Cleaning project:[ 02_Find_Numbers_with_Even_Number_of_Digits - Debug ]----------"
	@cd "02_Find_Numbers_with_Even_Number_of_Digits" && "$(MAKE)" -f  "02_Find_Numbers_with_Even_Number_of_Digits.mk" clean
