.PHONY: clean All

All:
	@echo "----------Building project:[ Palindromic_String - Debug ]----------"
	@cd "Palindromic_String" && "$(MAKE)" -f  "Palindromic_String.mk"
clean:
	@echo "----------Cleaning project:[ Palindromic_String - Debug ]----------"
	@cd "Palindromic_String" && "$(MAKE)" -f  "Palindromic_String.mk" clean
