.PHONY: clean All

All:
	@echo "----------Building project:[ Bricks_Game - Debug ]----------"
	@cd "Bricks_Game" && "$(MAKE)" -f  "Bricks_Game.mk"
clean:
	@echo "----------Cleaning project:[ Bricks_Game - Debug ]----------"
	@cd "Bricks_Game" && "$(MAKE)" -f  "Bricks_Game.mk" clean
