.PHONY: clean All

All:
	@echo "----------Building project:[ Lift_queries - Debug ]----------"
	@cd "Lift_queries" && "$(MAKE)" -f  "Lift_queries.mk"
clean:
	@echo "----------Cleaning project:[ Lift_queries - Debug ]----------"
	@cd "Lift_queries" && "$(MAKE)" -f  "Lift_queries.mk" clean
