.PHONY: clean All

All:
	@echo "----------Building project:[ 04_Rearrange_an_array - Debug ]----------"
	@cd "04_Rearrange_an_array" && "$(MAKE)" -f  "04_Rearrange_an_array.mk"
clean:
	@echo "----------Cleaning project:[ 04_Rearrange_an_array - Debug ]----------"
	@cd "04_Rearrange_an_array" && "$(MAKE)" -f  "04_Rearrange_an_array.mk" clean
