.PHONY: clean All

All:
	@echo "----------Building project:[ 01_Rotate_Array - Debug ]----------"
	@"$(MAKE)" -f  "01_Rotate_Array.mk"
clean:
	@echo "----------Cleaning project:[ 01_Rotate_Array - Debug ]----------"
	@"$(MAKE)" -f  "01_Rotate_Array.mk" clean
