.PHONY: clean All

All:
	@echo "----------Building project:[ 03_Rotate_Array_Reversal_Algorithm - Debug ]----------"
	@cd "03_Rotate_Array_Reversal_Algorithm" && "$(MAKE)" -f  "03_Rotate_Array_Reversal_Algorithm.mk"
clean:
	@echo "----------Cleaning project:[ 03_Rotate_Array_Reversal_Algorithm - Debug ]----------"
	@cd "03_Rotate_Array_Reversal_Algorithm" && "$(MAKE)" -f  "03_Rotate_Array_Reversal_Algorithm.mk" clean
