.PHONY: clean All

All:
	@echo "----------Building project:[ Remove_duplicates_from_sorted_array - Debug ]----------"
	@cd "Remove_duplicates_from_sorted_array" && "$(MAKE)" -f  "Remove_duplicates_from_sorted_array.mk"
clean:
	@echo "----------Cleaning project:[ Remove_duplicates_from_sorted_array - Debug ]----------"
	@cd "Remove_duplicates_from_sorted_array" && "$(MAKE)" -f  "Remove_duplicates_from_sorted_array.mk" clean
